//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod commit;
pub mod fts_packages;
pub mod history;
pub mod package_changes;
pub mod package_dependencies;
pub mod package_duplicate;
pub mod package_errors;
pub mod package_spec;
pub mod package_testing;
pub mod package_versions;
pub mod packages;
pub mod tree_branches;
pub mod trees;
