//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "package_testing")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub package: String,
    pub version: String,
    pub defines_path: String,
    pub spec_path: String,
    #[sea_orm(primary_key)]
    pub tree: String,
    #[sea_orm(primary_key)]
    pub branch: String,
    pub commit: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
