//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "package_errors")]
pub struct Model {
    pub package: String,
    pub err_type: String,
    pub message: String,
    pub path: String,
    pub tree: String,
    pub branch: String,
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
