//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "package_testing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub package: String,
    pub version: String,
    pub defines_path: String,
    pub spec_path: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tree: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub branch: String,
    pub commit: String,
    pub full_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
